/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./src/**/*.{js,ts,jsx,tsx,mdx}",
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "tertiary-container": "#633a14",
        "on-primary": "#ffffff",
        outline: "#70787b",
        "tertiary-fixed-dim": "#f7ba89",
        primary: "#00333c",
        "surface-container-highest": "#e1e3e4",
        "on-tertiary": "#ffffff",
        "on-surface": "#191c1d",
        "surface-bright": "#f8f9fa",
        "secondary-fixed-dim": "#b9c9ce",
        "surface-dim": "#d9dadb",
        "primary-container": "#004b57",
        "tertiary-fixed": "#ffdcc3",
        "surface-container-low": "#f3f4f5",
        background: "#f8f9fa",
        "surface-variant": "#e1e3e4",
        error: "#ba1a1a",
        "on-tertiary-fixed-variant": "#663d17",
        "on-secondary-fixed-variant": "#3a494d",
        "on-primary-fixed": "#001f25",
        "secondary-fixed": "#d5e5ea",
        "on-primary-fixed-variant": "#064e5a",
        "surface-container-lowest": "#ffffff",
        "on-secondary-fixed": "#0f1e21",
        "on-secondary-container": "#58676b",
        secondary: "#526165",
        "inverse-on-surface": "#f0f1f2",
        "primary-fixed": "#b2ecfa",
        "on-tertiary-container": "#dfa576",
        "inverse-primary": "#96d0de",
        "inverse-surface": "#2e3132",
        tertiary: "#482401",
        "primary-fixed-dim": "#96d0de",
        "secondary-container": "#d5e5ea",
        "error-container": "#ffdad6",
        "on-tertiary-fixed": "#2f1500",
        "surface-container-high": "#e7e8e9",
        "on-surface-variant": "#40484a",
        surface: "#f8f9fa",
        "on-primary-container": "#81bac8",
        "on-error": "#ffffff",
        "surface-tint": "#2a6673",
        "outline-variant": "#bfc8ca",
        "on-secondary": "#ffffff",
        "surface-container": "#edeeef",
        "on-error-container": "#93000a",
        "on-background": "#191c1d",
      },
      fontFamily: {
        headline: ["Noto Serif", "serif"],
        body: ["Plus Jakarta Sans", "sans-serif"],
        label: ["Plus Jakarta Sans", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
    },
  },
  plugins: [],
};
